apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kelloworld
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/kelloworld:0.0.1