apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: kelloworld
spec:
  revisionTemplate:
    metadata:
      labels:
       app: kelloworld
    spec:
      container:
        image: dev.local/kelloworld:0.0.2